        <footer>
            <p>&copy; 2026 ClownSS. All rights reserved.</p>
            <a href="<?php echo $selfLink; ?>" target="_self" title="Go to Top of the page"  hreflang="en">Click here to go to the top of the page</a>
            <br>
            <address><p>Contact us at: <a href="mailto:support@clownss.com.au">support@clownss.com.au</a></p></address>
            <p> Github Repo: </p>
            <a href="https://github.com/ThomasCrawley-105332287/ClownSS_AppliedWebProject_Part2" target="_blank">ClownSS Repository</a>
        </footer>
    </body>
</html>