        <footer>
            <p>&copy; 2026 ClownSS. All rights reserved.</p>
            <a href="<?php echo $selfLink; ?>" target="_self" title="Go to Top of the page"  hreflang="en">Click here to go to the top of the page</a>
            <br>
            <address><p>Contact us at: <a href="mailto:106016142@student.swin.edu.au">106016142@student.swin.edu.au</a></p></address>
            <p> Github Repo: </p>
            <a href="https://thomascrawley-105332287.github.io/ClownSS_AppliedWebProject_Part1/">ClownSS Repository</a>
            <p>Jira Link: </p>
            <a href="https://clownss.atlassian.net/jira/software/projects/CAWPP1/boards/1/backlog"> Jira Space</a>
        </footer>
    </body>
</html>